name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dependencies:
  build_runner: ^2.4.7
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^13.0.1
  http: ^1.1.2
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
